<a href="https://colab.research.google.com/github/wcolglazier/Additional-AI-Class-Content/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import numpy as np

NumPy is a Python library that helps us efficiently stores data and provides built in functions to make working with that data faster and more convenient.

In [60]:
data_one = np.array([1, 2, 3])
data_two = np.array([4, 5, 6])

Data is organized in row form, known as a NumPy array.

In [61]:
sum = data_one + data_two
print(sum)

[5 7 9]


In [62]:
product = data_one * data_two
print(product)

[ 4 10 18]


In [63]:
total = np.sum(data_one * data_two)
print(total)

32


In [64]:
dot_product = np.dot(data_one, data_two)
print(dot_product)


32


2d data

In [65]:
Data_one_2D = [[1, 2, 3],
          [4, 5, 6],
          [3, 2, 1]]


Data_two_2D = [[10, 9, 8],
          [7, 8, 9],
          [10, 11, 12]]


In [66]:
w = np.dot(Data_one_2D, Data_two_2D)

print(w)

[[ 54  58  62]
 [135 142 149]
 [ 54  54  54]]


In [73]:
Data_one_2D = [[1, 2],
          [4, 5],
]


Data_two_2D = [[10, 9],
          [7, 8],
]


w = np.dot(Data_one_2D, Data_two_2D)

print(w)

[[24 25]
 [75 76]]


$
w[i, j] = \sum_{k} \text{Data_one_2D}[i, k] \cdot \text{Data_two_2D}[k, j]
$




#### Row 1:

$$
w[0, 0] = (1 \cdot 10) + (2 \cdot 7) = 10 + 14 = 24
$$
$$
w[0, 1] = (1 \cdot 9) + (2 \cdot 8) = 9 + 16 = 25
$$

#### Row 2:
$$
w[1, 0] = (4 \cdot 10) + (5 \cdot 7) = 40 + 35 = 75
$$
$$
w[1, 1] = (4 \cdot 9) + (5 \cdot 8) = 36 + 40 = 76
$$
